---
driver:
  name: docker

provisioner:
  hosts:  test-kitchen
  name: ansible_playbook
  roles_path:  roles
  require_ansible_repo:  true
  ansible_verbose:  true
  ansible_version:  latest
  require_chef_for_busser:  false
  playbook:  site.yml
  

platforms:
  - name: ubuntu-16.04

suites:
  - name: default

verifier:
  name: inspec
  inspec_tests:
    - test/integration/default

